# 여러 가지 검증을 위한 기록

## Embedding vs. One-hot Vector
Question: 왜 embedding을 사용해야 하는가 One-hot Vector를 사용하지 말아야 할 이유가 있는가?

### Integer Encoding을 이용한 시퀀스 비교

In [41]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

preprocessed_syscall_seqeunce = [
    ['A', 'B', 'C', 'B', 'W','V'],
    ['X','Y','X','Y','A', 'B', 'C', 'B'],
    ['M','N','M','N','D', 'E', 'F', 'E']
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_syscall_seqeunce)
encoded_syscall_sequence = tokenizer.texts_to_sequences(preprocessed_syscall_seqeunce)

max_len = max(len(item) for item in encoded_syscall_sequence)
print('최대 길이 :',max_len)

from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_syscall_sequence = pad_sequences(encoded_syscall_sequence, padding='post')
for i, seq in enumerate(padded_syscall_sequence):
    print(f"{i}번 째: {seq}")


from numpy import dot
from numpy.linalg import norm
def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))
print()
print(f"{padded_syscall_sequence[0]}\n{padded_syscall_sequence[1]} \t- ", cos_sim(padded_syscall_sequence[0], padded_syscall_sequence[1]),"\n")
print(f"{padded_syscall_sequence[0]}\n{padded_syscall_sequence[2]} \t- ", cos_sim(padded_syscall_sequence[0], padded_syscall_sequence[2]),"\n")
print(f"{padded_syscall_sequence[1]}\n{padded_syscall_sequence[2]} \t- ", cos_sim(padded_syscall_sequence[1], padded_syscall_sequence[2]),"\n")

최대 길이 : 8
0번 째: [ 2  1  3  1  9 10  0  0]
1번 째: [4 5 4 5 2 1 3 1]
2번 째: [ 6  7  6  7 11  8 12  8]

[ 2  1  3  1  9 10  0  0]
[4 5 4 5 2 1 3 1] 	-  0.42064341126964216 

[ 2  1  3  1  9 10  0  0]
[ 6  7  6  7 11  8 12  8] 	-  0.6713092477665927 

[4 5 4 5 2 1 3 1]
[ 6  7  6  7 11  8 12  8] 	-  0.821601387744398 



### One-hot vector를 이용한 시퀀스 비교

In [55]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from sklearn.metrics.pairwise import cosine_similarity


preprocessed_syscall_seqeunce = [
    ['A', 'B', 'C', 'B', 'W','V'],
    ['X','Y','X','Y','A', 'B', 'C', 'B'],
    ['A','N','B','N','C', 'N', 'B', 'N']
]

encoded_syscall_sequence = tokenizer.texts_to_sequences(preprocessed_syscall_seqeunce)
padded_syscall_sequence = pad_sequences(encoded_syscall_sequence, padding='post')

one_hot_syscall_sequence = to_categorical(padded_syscall_sequence)
print(one_hot_syscall_sequence)

print(cosine_similarity(one_hot_syscall_sequence,one_hot_syscall_sequence))

[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]]


ValueError: Found array with dim 3. check_pairwise_arrays expected <= 2.